### ISSUE TITLE
Not open source

### ISSUE THREAD

**Issue by TechnologyClassroom** [TwBurn/Nobelia#2]
The README.md file states `This is the Open Source version of Nobelia.` and `The source code and assets in this repository are meant for personal and/or educational use only` and `Distributing a compiled version of Nobelia in any form (digital or physical) is prohibited`.

Restricting against redistribution and use is not open source according to the Open Source Initiative (OSI).

I would recommend choosing a software license that is free software and open source.  Until then, the correct term for this software is source available.

**Comment by TwBurn** [comment]
Removed statement

**Comment by TechnologyClassroom** [comment]
Removing the `Distributing a compiled version of Nobelia in any form (digital or physical) is prohibited.` line helps, but the project is still not open source without a license so the issue is not resolved yet. I searched the repo for license and only found the readme and `./build/COPYRGHT.TXT` which only reference the various assets most of which are not present. Without a license, the code is [source available](https://en.wikipedia.org/wiki/Source_available).

To really solve the issue, create a `LICENSE` file in the root directory and GitHub will help you pick a license.
